### ISSUE TITLE
Cleanup error page layout

### ISSUE THREAD

**Issue by frdmn** [frdmn/frd.mn#8]

**Comment by rnarian** [comment]
What's that suppose to mean?

**Comment by frdmn** [comment]
no idea :trollface: ...

**Comment by rnarian** [comment]
Quick fix. Might be revamped later...

![bildschirmfoto 2015-05-03 um 12 11 21](https://cloud.githubusercontent.com/assets/1174951/7444639/97571a64-f18d-11e4-898e-f8a97e9c52e4.png)
